name: deploy_prod

on:
  push:
    branches: [ master ]

jobs:
  Build Test Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Setup node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
          YARN_CACHE_FOLDER: ~/.yarncache
        with:
          path: ~/.yarncache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-


      - name: 'Install dependencies'
        env:
          YARN_CACHE_FOLDER: ~/.yarncache
        run: yarn

      - name: 'Lists everything'
        run: pwd && ls -la .

      - name: 'Test'
        env:
          NODE_ENV: CI
        run: yarn test:coverage

      - name: 'Deploy coverage'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build'
        env:
          NODE_ENV: production
        run: yarn build

      - name: 'Deploy to production'
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod -C'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
